### ISSUE TITLE
Download Subtitle from video

### ISSUE THREAD

**Issue by HorselessName** [sheodox/jimaku-player#17]
Hi. 

Could you implement a function to download the video subtitle?
Or to change the size of the subtitle of the video itself without uploading it.

But if its not possible to change the size of the subtitle in the video, let us download the official SRT from Crunchyroll so we can upload using the extension and then change the size.

Im watching Attack on Titan on Crunchroll and it does have the subtitle in my language but i cant find a way to download the srt subtitle...
It would be nice to download the subtitle from the video so i can upload via Jimaku Player...

**Comment by sheodox** [comment]
I don't think it'd be possible to provide a way to download the subtitles from Crunchyroll. The location their subtitles are downloaded from is a really long random looking URL (you can find it in your browser's dev tools network tab) and I'm not sure how to figure out what that URL is. They actually use ASS format subtitles so it'd look like this: https://en.wikipedia.org/wiki/SubStation_Alpha#Advanced_SubStation_Alpha

I also don't think they would like it if I provided a way to download their stuff, I could see it being a legal mess so I'm going to stay out of it!

For technical reasons I don't think it'd be very easy to change the size of the built-in subtitles effectively.

Best of luck finding an alternative solution!
