### ISSUE TITLE
Buttons unclickable on crunchyroll

### ISSUE THREAD

**Issue by spookyjj** [sheodox/jimaku-player#20]
The 'skip subtitling for this episode' and 'select a subtitle file to begin' buttons suddenly became unclickable on crunchyroll (I didn't change/modify/update anything it just suddenly occurred, everything still works on VRV tho). The buttons appear when i open a new video like normal, only problem is they aren't working (fullscreen same thing). I tried reinstalling the script no luck though

https://user-images.githubusercontent.com/39008772/117382897-80e50500-aead-11eb-8f0a-584cc17ca4f6.mov

**Comment by sheodox** [comment]
Huh interesting. If you refresh the page does it only happen every time or just sometimes? Is this with the Crunchyroll beta?

**Comment by spookyjj** [comment]
Since it started it happens every time on both crs. I checked both cr beta and og cr, cleared cookies and logged in and out. (Also refreshed the page) before it stopped working today though it had worked with cr beta as well so its not an issue with cr beta specifically

**Comment by sheodox** [comment]
Which browser do you use? I couldn't get this to happen to me on Firefox but I'll keep trying.

**Comment by spookyjj** [comment]
Chrome (fully updated)

**Comment by RiverMatsumoto** [comment]
Hi, I actually am encountering the same issue on chrome. Buttons are unclickable. Just adding this so it is made aware.

**Comment by sheodox** [comment]
@spookyjj @RiverMatsumoto 
Thanks for the issue report! I just released a new version that should fix this.

If you click the Tampermonkey icon in your browser toolbar then hit "Utilities" then "Check for userscript updates" you should get the new version `0.5.2`. Let me know if this fixes it for you can I can close this issue.

![image](https://user-images.githubusercontent.com/3468630/117442344-4191d500-aefc-11eb-866b-672dae3b505b.png)

**Comment by spookyjj** [comment]
This fixed it for me, everything works now thanks 👍

**Comment by sheodox** [comment]
Great!
