### ISSUE TITLE
Subtitles text go outside of  video aspect ratio window

### ISSUE THREAD

**Issue by Phoenomenal** [sheodox/jimaku-player#34]
Hello, i use a 3440:1440p monitor which have 21:9 aspect ratio and when using jimaku extension text eventually go outside of video window to black boxes on right and left (because all modern anime have 16:9 aspect and older ones 4:3) Is it possible to lock jimaku to video aspect ratio so subs won't go outside video range? On 21:9 monitor it happened all the time and for most people using 16:9 i believe it happens when they watch older anime prior to about 2006 -2007 year when anime was still  shot in 4:3 aspect ratio mostly. 

In pictures below as example i used  both a 4:3 and 16:9 aspect ratio video .  As you can see subs go way outside of video window all the way to the corners.  
![Screenshot_3](https://user-images.githubusercontent.com/68902338/145670196-e97d6c20-3886-4806-940f-bafe71ece561.png)

![Screenshot_4](https://user-images.githubusercontent.com/68902338/145670308-65d98aac-2db9-4047-ac83-64b4c2dfa603.png)

**Comment by sheodox** [comment]
I've known this was an issue but nobody had said anything about it until now. I'll see what I can do, I've got an idea for how I might fix it! I planned on doing a lot of work on Jimaku Player in the coming weeks, I'll add this to my todo list.

Thanks for the report!

**Comment by sheodox** [comment]
Hey @Phoenomenal I just released a new version (0.6.3) that fixes this! There's now an "Aspect Ratio" setting in the tray. If you use VRV you can also set it by show so individual shows can be set to 4:3 manually while assuming 16:9 for the rest.

Let me know if this works for you!

![image](https://user-images.githubusercontent.com/3468630/148704323-ebcecbe8-f3d5-433d-8bd9-2c2e61bbe688.png)

You can update by clicking "Check for userscript updates" in the Tampermonkey menu
![image](https://user-images.githubusercontent.com/3468630/148704615-3033f097-90ec-45fd-ab18-0750afdc8a1a.png)

**Comment by Phoenomenal** [comment]
Works like a charm.   Using .ass  subs with auto option its set to 4:3 (tested on HunterxHunter 2011 remake which is 16:9 aspect ratio and Gintama 2006 which is 4:3)      .srt on the other scales to 16:9 by auto.   
But its not a problem since 16:9 and 4:3  options scale subs correctly.   So i will just use 16:9 by default  and 4:3 for older anime which have this aspect ratio.
Thank you!!!

**Comment by sheodox** [comment]
Great!! I'm glad it's working for you now! And yeah not really much I can do about that 4:3 srt thing on auto. I might investigate more again someday but with the option there it should be good enough!
