### ISSUE TITLE
Docker Error during migration run

### ISSUE THREAD

**Issue by jablazr** [sheodox/jimaku-player#35]
Hello,
I'm trying to setup this project on my machine but I can't get it to work.

I'm new to Docker and this is my first time using it but here is my attempt:
When I run `docker-compose up` I get an error:
```
[+] Running 9/9
 - postgres Pulled                                                                                                17.1s
   - 59bf1c3509f3 Already exists                                                                                   0.0s
   - c50e01d57241 Pull complete                                                                                    0.8s
   - a0646b0f1ead Pull complete                                                                                    0.9s
   - 08018e47fc43 Pull complete                                                                                   12.0s
   - 6014f2775635 Pull complete                                                                                   12.1s
   - 85760f97d4b8 Pull complete                                                                                   12.2s
   - 3e07f59f91db Pull complete                                                                                   12.3s
   - 3f86c399b0a1 Pull complete                                                                                   12.5s
[+] Building 1.1s (11/11) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 34B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/node:12-alpine                                                  0.8s
 => [dev 1/6] FROM docker.io/library/node:12-alpine@sha256:8fad09b7620b2bc715cbba92e3313c64a797e453f560118576f174  0.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 72B                                                                                   0.0s
 => CACHED [dev 2/6] RUN apk add --no-cache ffmpeg                                                                 0.0s
 => CACHED [dev 3/6] WORKDIR /usr/src/app                                                                          0.0s
 => CACHED [dev 4/6] RUN npm i -g typeorm                                                                          0.0s
 => CACHED [dev 5/6] COPY package*.json ./                                                                         0.0s
 => CACHED [dev 6/6] RUN npm install                                                                               0.0s
 => exporting to image                                                                                             0.1s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:33969ca22b78682d2587143698196cd5c8d48a7290f0514f5b5b91762ef5f182                       0.0s
 => => naming to docker.io/library/jimaku-player_app                                                               0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 4/4
 - Network jimaku-player_default       Created                                                                     0.8s
 - Volume "jimaku-player_postgres"     Created                                                                     0.0s
 - Container jimaku-player_postgres_1  Created                                                                     1.7s
 - Container jimaku-player_app_1       Created                                                                     0.2s
Attaching to app_1, postgres_1
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  |
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  |
postgres_1  | Data page checksums are disabled.
postgres_1  |
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1  | creating subdirectories ... ok
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | selecting default max_connections ... 100
postgres_1  | selecting default shared_buffers ... 128MB
postgres_1  | selecting default time zone ... UTC
postgres_1  | creating configuration files ... ok
postgres_1  | running bootstrap script ... ok
postgres_1  | performing post-bootstrap initialization ... sh: locale: not found
postgres_1  | 2021-12-21 11:18:42.037 UTC [30] WARNING:  no usable system locales were found
postgres_1  | ok
postgres_1  | syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
postgres_1  | ok
postgres_1  |
postgres_1  |
postgres_1  | Success. You can now start the database server using:
postgres_1  |
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1  |
postgres_1  | waiting for server to start....2021-12-21 11:18:43.144 UTC [36] LOG:  starting PostgreSQL 13.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
postgres_1  | 2021-12-21 11:18:43.150 UTC [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2021-12-21 11:18:43.177 UTC [37] LOG:  database system was shut down at 2021-12-21 11:18:42 UTC
postgres_1  | 2021-12-21 11:18:43.188 UTC [36] LOG:  database system is ready to accept connections
postgres_1  |  done
postgres_1  | server started
postgres_1  | CREATE DATABASE
postgres_1  |
postgres_1  |
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1  |
postgres_1  | waiting for server to shut down...2021-12-21 11:18:43.515 UTC [36] LOG:  received fast shutdown request
postgres_1  | .2021-12-21 11:18:43.520 UTC [36] LOG:  aborting any active transactions
postgres_1  | 2021-12-21 11:18:43.521 UTC [36] LOG:  background worker "logical replication launcher" (PID 43) exited with exit code 1
postgres_1  | 2021-12-21 11:18:43.521 UTC [38] LOG:  shutting down
postgres_1  | 2021-12-21 11:18:43.549 UTC [36] LOG:  database system is shut down
postgres_1  |  done
postgres_1  | server stopped
postgres_1  |
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  |
postgres_1  | 2021-12-21 11:18:43.676 UTC [1] LOG:  starting PostgreSQL 13.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
postgres_1  | 2021-12-21 11:18:43.676 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2021-12-21 11:18:43.676 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2021-12-21 11:18:43.690 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2021-12-21 11:18:43.706 UTC [50] LOG:  database system was shut down at 2021-12-21 11:18:43 UTC
postgres_1  | 2021-12-21 11:18:43.717 UTC [1] LOG:  database system is ready to accept connections
app_1       | Error during migration run:
app_1       | TypeORMError: No connection options were found in any orm configuration files.
app_1       |     at new TypeORMError (/usr/local/lib/node_modules/typeorm/error/TypeORMError.js:9:28)
app_1       |     at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/typeorm/connection/ConnectionOptionsReader.js:38:35)
app_1       |     at step (/usr/local/lib/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
app_1       |     at Object.next (/usr/local/lib/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
app_1       |     at fulfilled (/usr/local/lib/node_modules/typeorm/node_modules/tslib/tslib.js:114:62)
app_1 exited with code 1
```
It says: `TypeORMError: No connection options were found in any orm configuration files.`

I have tried building an image myself and running it but then I don't have a postgres image and I get the following error when I run it:
```
Error during migration run:
Error: getaddrinfo EAI_AGAIN postgres
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'postgres'
}
```

I have created the following `.env` file in my project root:
```
PGUSER=user
PGPASSWORD=password
PGDATABASE=jimaku-player
```

I don't know what to do now. Any help is very much appreciated!

**Comment by sheodox** [comment]
I think you need to add:
```
PGHOST=postgres
PGPORT=5432
```
To the `.env` file as well, because the app can be run outside of docker in which case you'd use `PGHOST=localhost` and `PGPORT=whatever you want` (you'd need to uncomment the port bindings in docker-compose.yml so it will expose the database out of the container).

Additionally instead of just doing `docker-compose up` you should use `./run.sh dev` because it needs to merge two config files (the base `docker-compose.yml` and either `docker-compose.dev.yml` or `docker-compose.prod.yml`). If you're not on linux or something you could probably just do `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build`.

Also, the front end for the dev site expects content in a pretty specific format (an MP4-DASH'd video, and a matching json file  that includes the dash manifest xml, some info about the video itself, and whatever subtitles were extracted from the video). I have a separate project called [jimaku-player-ingest](https://github.com/sheodox/jimaku-player-ingest) for generating these. I think it just works on `.mkv` source videos at the moment, and I'm pretty sure there are issues if the source video has more than 2 channel audio? Either way it's not really complete at the moment and probably pretty tedious to work with, sorry! Nobody else has been interested in working on it so I haven't improved that stuff in a while.

**Comment by sheodox** [comment]
Actually it looks like those .env config options are the fallbacks in the typeorm config so that part should have worked regardless. I think the issue is the need to run docker-compose merging the two config files.

**Comment by sheodox** [comment]
Sorry for the comment spam, but FWIW I'm planning on doing a major refactor/rewrite somewhat soon so any issues you have now I'll try and fix when I do that.

**Comment by jablazr** [comment]
Okay, so I managed to get both containers to start and run by using `./run.sh dev`.
But when I attach a shell to the container `jimaku-player-app` and try to run `npm run build:dev` I get this error:
```
9cc2cc620e3c:/usr/src/app# npm run build:dev

> jimaku-player@0.0.1 build:dev /usr/src/app
> webpack --mode development --watch


webpack is watching the files…


Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: 90a9951b0473f336745f
Version: webpack 4.41.6
Time: 50ms
Built at: 12/21/2021 3:03:28 PM

ERROR in Entry module not found: Error: Can't resolve './src' in '/usr/src/app'
```

And when I look at my container logs in Docker Desktop I see:
```
query: SELECT * FROM current_schema()
query: SHOW server_version;
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'typeorm_metadata'
query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
No migrations are pending

> jimaku-player@0.0.1 server:dev /usr/src/app
> nodemon server/server.js

[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server/server.js index.js`
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/usr/src/app/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[nodemon] app crashed - waiting for file changes before starting...
```
This error goes away when I add an `index.js` file in the app root:
```
[nodemon] restarting due to changes...
[nodemon] starting `node server/server.js index.js`
Hello world
[nodemon] clean exit - waiting for changes before restart
```

I might have missed a step, maybe I have to add a video to `/videos` before running `./run.sh dev`?
I tried to add an mp4 I had on my drive to `/videos` while the container was already running to see if something would change but it didn't. I'm thinking that maybe it has to be in that special format you mentioned before.

`http://localhost:3500/` does not send any data back and I tried the routes `/v`, `/videos` & `/image`.
I will be grateful for any help you can provide.

**Comment by sheodox** [comment]
I always run the builds on my host machine, and I've never really tried running the builds inside the container. I usually split my terminal up so I can run:
* `./run.sh dev`
* `npm run build-server:dev`
* `npm run build:dev`
all in a column so I can see it all at once.

![image](https://user-images.githubusercontent.com/3468630/147000593-a7d1b413-ec9e-471f-8c7b-30d3e0d5ce2e.png)

Out of curiosity, is there something you're looking to do in particular on Jimaku Player?

If you need I could work on generating a demo video/metadata you could use to test stuff.

**Comment by jablazr** [comment]
I intend to work on two things that would be useful to me:

Firstly, I want to fix a bug that makes the subtitles in the subtitle search go out of bounds instead of adding a scroll wheel:
![image](https://user-images.githubusercontent.com/22749383/147002609-ed30a39c-70ee-41fb-a74a-b83870e156cc.png)
Maybe it has to do with my browser (Chrome), an incompatible extension (Dark Reader, Improve Crunchyroll, Adblock Plus) or that I'm using the Crunchyroll Beta site. I haven't tested these things yet.

Secondly, I want to add a way to input an offset alignment manually:
![image](https://user-images.githubusercontent.com/22749383/147003136-556f9b50-75ae-4965-b9b6-5a6b17501cd8.png)

In my case, this would be useful because I have a list of subtitles for Boruto (LOL) that have 3 different alignments throughout the episode but are similar for each of the episodes.

I would like to collaborate and help out with these things and with your goals if I'm able to.

**Comment by sheodox** [comment]
Ah oops, I guess I hadn't tested Chrome out for that first thing, that's definitely a bug, I don't remember it looking like that!

You can already input an alignment manually, there's a button that's covered up by the subtitle buttons in your first screenshot for that! I actually had a similar problem with One Piece having multiple alignments throughout the episode, which is why there are those "Switch to a previous alignment" buttons along with a preview of what sub is shown then lol. No judgement on Boruto, I've got friends who watch it and I'm considering watching it and Naruto someday.

That'd be cool! I have next week off of work so I was planning on doing a lot of it then. I think it'd be easier to help out once I've done things, as I'll be changing a ton of stuff it'd be hard to collaborate, but after that thing should be more manageable and I'd appreciate any help you're willing to give then! Thanks!

**Comment by jablazr** [comment]
Now I see the manual offset button! ;D
I currently don't have a lot of time because of my midterms until mid-January, so I can't be very active until then.

I also think that it will be easier to help out once you have rewritten things. I will follow your work until then!

**Comment by sheodox** [comment]
@jablazr 

I've made most of my big changes now. I still have a few things to do but the bulk of the rewrite is done. I also updated the contributing doc, it was super out of date!

The dev server now supports plain .mp4 files again, no Postgres anymore (so no need for a `.env`), everything is written in TS, replaced Webpack with Vite (with hot module replacement so your browser auto-updates with changes when developing), I moved a ton of files around, and I updated the general look of things. I still have a few things I want to do in the coming days but it shouldn't be another 120 file commit :wink: 

I wasn't able to reproduce that overflow issue you were having though, does that still happen to you with my changes?

Either way, should be more easy to make changes if you're still planning on trying stuff out.

**Comment by jablazr** [comment]
Alright! I will check out the changes and try to get the code running on my machine. I will also see if my overflow problem persists. Thank you for the update!

**Comment by jablazr** [comment]
The subtitles don't overflow anymore :)
<img width="261" alt="image" src="https://user-images.githubusercontent.com/22749383/148657806-9a566bd7-bb00-4055-8d7f-44d42c1f23bc.png">
I also really like the new UI!

**Comment by sheodox** [comment]
Woo, glad it's fixed, and thanks!
