### ISSUE TITLE
How to make extension popup appear a bit lower on screen ?

### ISSUE THREAD

**Issue by Antivan28** [sheodox/jimaku-player#37]
Hello,  is there any way to move extension popup a bit lower.  The thing is i use a theater mode extension (https://chrome.google.com/webstore/detail/crunchyroll-theater/dpggfkaifdajfnfkogccmpfinnffbjgo)  which hide header and make it  appear when you hover mouse on top of the screen.  And because of that i cant either click on "select subtitle file you begin"  or "cancel"  button.    Maybe i can edit some lines in tampermonkey script editor myself ?  

 A few images below for better understanding :  

This header prevents me from choosing any option on jimaku pop up
![Screenshot_12](https://user-images.githubusercontent.com/98211067/150633594-40c0688d-0d25-47f5-ab13-88e69750b5f9.png)

If somehow i could move this pop up a bit lower to red zone at least like in picture below i could click these options.
![Screenshot_14](https://user-images.githubusercontent.com/98211067/150633653-03a99543-954b-4e6f-b0df-073a3656491d.png)

**Comment by sheodox** [comment]
I'll have to think it over, but maybe it'd be better if I moved the buttons to the center of the screen? Nobody's really going to be watching anime and leaving those buttons up anyway, so as long as they're clickable, anywhere on the screen would probably be fine. What do you think about that?

**Comment by Antivan28** [comment]
> I'll have to think it over, but maybe it'd be better if I moved the buttons to the center of the screen? Nobody's really going to be watching anime and leaving those buttons up anyway, so as long as they're clickable, anywhere on the screen would probably be fine. What do you think about that?

Yes, great idea.   I think everyone  click either one of these options first thing  as video starts to make pop up disappear  so it doesn't really matter if those buttons will be at the center of the screen.

**Comment by sheodox** [comment]
@Antivan28 Just released a fix for this! You can manually update through tampermonkey by hitting this button:
![image](https://user-images.githubusercontent.com/3468630/150718028-f754e805-f674-4467-ac9e-fd22ae8fdc2c.png)

**Comment by Antivan28** [comment]
Awesome,  thanks ! 👍
