### ISSUE TITLE
Compatibility with crpiframeplayer ?

### ISSUE THREAD

**Issue by HorselessName** [sheodox/jimaku-player#38]
Hello there!

I noticed that when using the script iFramePlayer alongside Jimaku Player only iFramePlayer works but Jimaku Player doesnt...
Any chance that this compatibility between the two scripts becomes a reality?

> https://github.com/luiz-lp/crpiframeplayer

Thanks!

**Comment by sheodox** [comment]
@HorselessName I'm not really sure, what does that do?

**Comment by sheodox** [comment]
I don't think I'm going to work on this, I can't really tell what it does and I don't think many people would find a use for it to justify the effort.
