### ISSUE TITLE
ASS subtitle fails to load if it references undefined style

### ISSUE THREAD

**Issue by HenryHu** [sheodox/jimaku-player#46]
I have an ass subtitle which failed to be loaded. The console says

[Jimaku Player] ASS parse error TypeError: i is undefined
    t moz-extension://e38ae3e1-e749-444b-b424-b00840fc2185/userscripts/字幕プレーヤー.user.js?id=2d653c48-832e-45c1-a650-911e8d7e8e86:188
    parseSubOverrideTags moz-extension://e38ae3e1-e749-444b-b424-b00840fc2185/userscripts/字幕プレーヤー.user.js?id=2d653c48-832e-45c1-a650-911e8d7e8e86:187
    rs moz-extension://e38ae3e1-e749-444b-b424-b00840fc2185/userscripts/字幕プレーヤー.user.js?id=2d653c48-832e-45c1-a650-911e8d7e8e86:185
    u moz-extension://e38ae3e1-e749-444b-b424-b00840fc2185/userscripts/字幕プレーヤー.user.js?id=2d653c48-832e-45c1-a650-911e8d7e8e86:196
    onload moz-extension://e38ae3e1-e749-444b-b424-b00840fc2185/userscripts/字幕プレーヤー.user.js?id=2d653c48-832e-45c1-a650-911e8d7e8e86:196
[字幕プレーヤー.user.js:185:199](moz-extension://e38ae3e1-e749-444b-b424-b00840fc2185/userscripts/%E5%AD%97%E5%B9%95%E3%83%97%E3%83%AC%E3%83%BC%E3%83%A4%E3%83%BC.user.js?id=2d653c48-832e-45c1-a650-911e8d7e8e86)
[Jimaku Player] Error occurred parsing this line 
Object { dataType: "dialogue", layer: "0", start: "0:00:44.85", end: "0:00:46.85", style: "ED11", name: "", marginL: "0", marginR: "0", marginV: "0", effect: "", … }

I realized the reason is that the style referenced at this line ("ED11") is not defined.

Although the file is problematic, at least we should still load the subtitle (maybe with the default / fallback style?), I think.

**Comment by sheodox** [comment]
Thanks for the report, and thanks for the investigation! I just released an update, please let me know if that fixes it.

You can update by clicking Tampermonkey in your browser toolbar and click "Utilities", then "Check for Userscript Updates"

**Comment by HenryHu** [comment]
Thanks! Somehow I need to manually enable "Check for updates" in the script's settings page.
It works now!

**Comment by sheodox** [comment]
Huh interesting, I think that happens if you manually tweak the script but maybe there are other reasons.

Thanks for testing, and thanks again for the report! :)
